package de.fhluebeck.group3.model;

/**
 * The Ingredient is mapped with Ingredient table in DB.
 * 
 * @author Yichen.Hua on 2018/05/13.
 */
public final class Ingredient {

	/**
	 * static strings for units -> kilogram, gram, liter, ml
	 */
	public static final String KILOGRAM = "kg";
	public static final String GRAM = "g";
	public static final String LITER = "L";
	public static final String MILLIONLITTER = "ml";
	public static final String TABLE_SPOON = "tablespoon";
	public static final String PIECES = "pieces";
	public static final String CLOVES = "cloves";
	public static final String CUPS = "cups";

	/**
	 * id of the ingredient.
	 */
	private Integer ingredientID;

	/**
	 * name of the ingredient.
	 */
	private String ingredientName;

	/**
	 * quantity of ingredient.
	 */
	private Double quantity;

	/**
	 * id of the recipe this ingredient belongs to.
	 */
	private Integer recipeID;

	/**
	 * unit of quantity.
	 */
	private String unit;
	
	/**
	 * Status of user: 1 for valid 0 for deleted.
	 */
	private Integer status;

	/**
	 * comments of recipe
	 */
	private String comment;

	/** ==============Constructors============== */
	/**
	 * default constructor.
	 */
	public Ingredient() {
		super();
	}

	/**
	 * constructor with attributes except ingredientID -> for insertions;
	 */
	public Ingredient(String ingredientName, Double quantity, Integer recipeID, String unit, String comments) {
		this(null, ingredientName, quantity, recipeID, unit, comments);
	}

	/**
	 * constructor of all attributes. -> Do not set ingredientID , it is
	 * auto-generated by database. Meanwhile, the unit should be final attributes
	 * within this Ingredient.
	 */
	public Ingredient(Integer ingredientID, String ingredientName, Double quantity, Integer recipeID, String unit,
			String comment) {
		super();
		this.ingredientID = ingredientID;
		this.ingredientName = ingredientName;
		this.quantity = quantity;
		this.recipeID = recipeID;
		this.unit = unit;
		this.comment = comment;
		this.status = 1;
	}

	/** ==============Getters and setters.============== */
	/**
	 * @return the ingredientID
	 */
	public Integer getIngredientID() {
		return ingredientID;
	}

	/**
	 * @param ingredientID
	 *            the ingredientID to set
	 */
	public void setIngredientID(Integer ingredientID) {
		this.ingredientID = ingredientID;
	}

	/**
	 * @return the ingredientName
	 */
	public String getIngredientName() {
		return ingredientName;
	}

	/**
	 * @param ingredientName
	 *            the ingredientName to set
	 */
	public void setIngredientName(String ingredientName) {
		this.ingredientName = ingredientName;
	}

	/**
	 * @return the quantity
	 */
	public Double getQuantity() {
		return quantity;
	}

	/**
	 * @param quantity
	 *            the quantity to set
	 */
	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	/**
	 * @return the recipeID
	 */
	public Integer getRecipeID() {
		return recipeID;
	}

	/**
	 * @param recipeID
	 *            the recipeID to set
	 */
	public void setRecipeID(Integer recipeID) {
		this.recipeID = recipeID;
	}

	/**
	 * @return the unit
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * @param unit
	 *            the unit to set
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * @param comment
	 *            the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
	
	/**
	 * @return the status
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * @param status
	 *            the status to set
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * Override toString method, print basic information of an ingredient.
	 */
	@Override
	public String toString() {
		return "Ingredient [ingredientID=" + ingredientID + ", ingredientName=" + ingredientName + ", quantity="
				+ quantity + ", recipeID=" + recipeID + ", unit=" + unit + ", status=" + status + ", comment=" + comment
				+ "]";
	}

}
