package de.group3.model;

/**
 * The Ingredient is mapped with Ingredient table in DB.
 * 
 * @author Yichen.Hua on 2018/05/13.
 */
public final class Ingredient {

	/**
	 * static strings for units -> kilogram, gram, liter, ml
	 */
	public static final String KILOGRAM = "KG";
	public static final String GRAM = "G";
	public static final String LITER = "L";
	public static final String MILLIONLITTER = "ML";

	/**
	 * id of the ingredient.
	 */
	private Integer ingredientID;

	/**
	 * name of the ingredient.
	 */
	private String ingredientName;

	/**
	 * quantity of ingredient.
	 */
	private Double quantity;

	/**
	 * id of the recipe this ingredient belongs to.
	 */
	private Integer recipeID;

	/**
	 * unit of quantity.
	 */
	private String unit;

	/** ==============Constructors============== */
	/**
	 * default constructor.
	 */
	public Ingredient() {
		super();
	}

	/**
	 * constructor with attributes except ingredientID -> for insertions;
	 */
	public Ingredient(String ingredientName, Double quantity, Integer recipeID, String unit) {
		this(null, ingredientName, quantity, recipeID, unit);
	}

	/**
	 * constructor of all attributes. -> Do not set ingredientID , it is
	 * auto-generated by database. Meanwhile, the unit should be final attributes
	 * within this Ingredient.
	 */
	public Ingredient(Integer ingredientID, String ingredientName, Double quantity, Integer recipeID, String unit) {
		super();
		this.ingredientID = ingredientID;
		this.ingredientName = ingredientName;
		this.quantity = quantity;
		this.recipeID = recipeID;
		this.unit = unit;
	}

	/** ==============Getters and setters.============== */
	/**
	 * @return the ingredientID
	 */
	public Integer getIngredientID() {
		return ingredientID;
	}

	/**
	 * @param ingredientID
	 *            the ingredientID to set
	 */
	public void setIngredientID(Integer ingredientID) {
		this.ingredientID = ingredientID;
	}

	/**
	 * @return the ingredientName
	 */
	public String getIngredientName() {
		return ingredientName;
	}

	/**
	 * @param ingredientName
	 *            the ingredientName to set
	 */
	public void setIngredientName(String ingredientName) {
		this.ingredientName = ingredientName;
	}

	/**
	 * @return the quantity
	 */
	public Double getQuantity() {
		return quantity;
	}

	/**
	 * @param quantity
	 *            the quantity to set
	 */
	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	/**
	 * @return the recipeID
	 */
	public Integer getRecipeID() {
		return recipeID;
	}

	/**
	 * @param recipeID
	 *            the recipeID to set
	 */
	public void setRecipeID(Integer recipeID) {
		this.recipeID = recipeID;
	}

	/**
	 * @return the unit
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * @param unit
	 *            the unit to set
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * Override toString method, print basic information of an ingredient.
	 */
	@Override
	public String toString() {
		return "Ingredient [ingredientID=" + ingredientID + ", ingredientName=" + ingredientName + ", quantity="
				+ quantity + ", recipeID=" + recipeID + ", unit=" + unit + "]";
	}

}
